CREATE TABLE TEST_CASE (
  TEST_CASE_ID VARCHAR2(40) NOT NULL,
  NODE_ID VARCHAR2(40) NOT NULL,
  TEST_CASE_TITLE VARCHAR2(1000),
  SUMMARY VARCHAR2(1000),
  PRECONDITIONS VARCHAR2(1000),
  RESULT VARCHAR2(1000),
  CREATE_TIME DATE,
  MODIFICATION_TIME DATE,
  EXECUTION_TYPE NUMBER(1) NOT NULL,
  CODE_PATH VARCHAR(100)
);

ALTER TABLE TEST_CASE ADD CONSTRAINT PK_TEST_CASE PRIMARY KEY (TEST_CASE_ID);
ALTER TABLE TEST_CASE ADD FOREIGN KEY (NODE_ID) REFERENCES NODES_HIERARCHY(ID);

COMMENT ON TABLE TEST_CASE IS '测试用例';
COMMENT ON COLUMN TEST_CASE.TEST_CASE_ID IS '测试用例ID';
COMMENT ON COLUMN TEST_CASE.NODE_ID IS '用例节点ID';
COMMENT ON COLUMN TEST_CASE.TEST_CASE_TITLE IS '测试用例名称';
COMMENT ON COLUMN TEST_CASE.SUMMARY IS '测试目的';
COMMENT ON COLUMN TEST_CASE.PRECONDITIONS IS '预期结果';
COMMENT ON COLUMN TEST_CASE.RESULT IS '测试结果';
COMMENT ON COLUMN TEST_CASE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN TEST_CASE.MODIFICATION_TIME IS '修改时间';
COMMENT ON COLUMN TEST_CASE.EXECUTION_TYPE IS '测试用例类型，1为手动，2为自动';
COMMENT ON COLUMN TEST_CASE.CODE_PATH IS '自动化测试代码路径';


CREATE TABLE TEST_CASE_STEPS (
  TEST_CASE_ID VARCHAR2(20) NOT NULL,
  STEP_NUMBER NUMBER(2) NOT NULL,
  ACTIONS VARCHAR2(1000),
  EXPECTED_RESULTS VARCHAR2(1000),
  ACTIVE NUMBER(1) NOT NULL,
  EXECUTION_TYPE NUMBER(1) NOT NULL,
  CODE_PATH VARCHAR2(100)
);
ALTER TABLE TEST_CASE_STEPS ADD CONSTRAINT PK_TEST_CASE_STEPS PRIMARY KEY (TEST_CASE_ID,STEP_NUMBER);

COMMENT ON TABLE TEST_CASE_STEPS IS '测试步骤';
COMMENT ON COLUMN TEST_CASE_STEPS.TEST_CASE_ID IS '测试用例ID';
COMMENT ON COLUMN TEST_CASE_STEPS.STEP_NUMBER IS '测试步骤序号';
COMMENT ON COLUMN TEST_CASE_STEPS.ACTIONS IS '测试步骤';
COMMENT ON COLUMN TEST_CASE_STEPS.EXPECTED_RESULTS IS '测试结果';
COMMENT ON COLUMN TEST_CASE_STEPS.ACTIVE IS '测试步骤状态，默认为1';
COMMENT ON COLUMN TEST_CASE_STEPS.EXECUTION_TYPE IS '测试步骤类型，1为手动，2为自动';
COMMENT ON COLUMN TEST_CASE_STEPS.CODE_PATH IS '自动化测试代码路径';

